### ISSUE TITLE
Dataset Structure fails to be ingested in case when there was no structure before

### ISSUE THREAD

**Issue by DementevNikita** [opendatadiscovery/odd-platform#638]
**Describe the bug**
Dataset Structure is not being properly ingested in cases when there was no structure before.
When there's a request to retrieve dataset structure, an error appears:
```
java.lang.NullPointerException: null
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:179) ~[na:na]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        *__checkpoint ⇢ Handler org.opendatadiscovery.oddplatform.controller.DatasetController#getDataSetStructureLatest(Long, ServerWebExchange) [DispatcherHandler]
        *__checkpoint ⇢ org.opendatadiscovery.oddplatform.config.CORSConfiguration$$Lambda$801/0x0000000801187ae0 [DefaultWebFilterChain]
        *__checkpoint ⇢ org.opendatadiscovery.oddplatform.config.ResourceProviderWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.opendatadiscovery.oddplatform.auth.filter.IngestionDataSourceFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/api/datasets/5/structure" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:179) ~[na:na]
                at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:na]
                at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
                at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
                at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
                at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
                at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
                at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
                at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
                at org.opendatadiscovery.oddplatform.mapper.DatasetVersionMapperImpl.mapDatasetFields(DatasetVersionMapperImpl.java:48) ~[main/:na]
                at org.opendatadiscovery.oddplatform.mapper.DatasetVersionMapperImpl.mapDatasetStructure(DatasetVersionMapperImpl.java:41) ~[main/:na]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) ~[reactor-core-3.4.13.jar:3.4.13]
                at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[reactor-core-3.4.13.jar:3.4.13]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169) ~[reactor-core-3.4.13.jar:3.4.13]
                at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.trySchedule(MonoSubscribeOn.java:189) ~[reactor-core-3.4.13.jar:3.4.13]
                at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onSubscribe(MonoSubscribeOn.java:134) ~[reactor-core-3.4.13.jar:3.4.13]
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) ~[reactor-core-3.4.13.jar:3.4.13]
                at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:192) ~[reactor-core-3.4.13.jar:3.4.13]
                at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.4.13.jar:3.4.13]
                at reactor.core.publisher.Mono.subscribe(Mono.java:4385) ~[reactor-core-3.4.13.jar:3.4.13]
                at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126) ~[reactor-core-3.4.13.jar:3.4.13]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.4.13.jar:3.4.13]
                at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.4.13.jar:3.4.13]
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
                at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Steps to Reproduce**

1. Ingest a bulk of datasets without any field structure
2. Add fields information to the payload and send it again

**Comment by DementevNikita** [comment]
Since Ingestion API is not transactional at the moment, this will be fixed in #624
